/// Flutter icons IconsCs
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconsCs
///      fonts:
///       - asset: fonts/IconsCs.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IconsCs {
  IconsCs._();

  static const _kFontFam = 'IconsCs';
  static const String? _kFontPkg = null;

  static const IconData clock = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData order = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profil = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pesanan = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beranda = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coupon = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopingbag = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData date = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData topping = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData voucher = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verification = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData time = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coins = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData finger = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coffee = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cash = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fire = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData note = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
